name: "3DPrinter-OctoPrint"
version: "2025.12.7"
slug: "3dprinter-octoprint"
description: "OctoPrint as an addon, no additional bells and whistles."
arch:
  - armv7
  - amd64
  - armhf
  - aarch64
url: "https://github.com/nwamasp-alt/ha-3dprinter-addons/tree/main/3dprinter-octoprint"
ingress: true
panel_icon: "mdi:printer-3d"
panel_title: "OctoPrint"
devices:
  - "/dev/i2c-0"
  - "/dev/i2c-1"
gpio: true
usb: true
uart: true
options:
  trusted_proxies: ""
  camera_url: ""
  safe_mode: false
schema:
  trusted_proxies: "str?"
  camera_url: "str?"
  safe_mode: "bool"
tmpfs: true
init: false
realtime: true
